"""
ML Evidence Adapter — the ONLY bridge between raw ML outputs and the Recommendation Engine.

Architectural rationale:
The RecommendationEngine must never consume raw ML payloads directly. This adapter
translates probabilistic ML outputs into deterministic, canonical evidence strings
that the engine already understands. This preserves the Evidence Graph architecture
and ensures the engine remains a pure function of canonical inputs.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel

# Schema version for ML results payloads. Any payload with a different
# version is rejected (abstained) rather than misinterpreted.
ML_RESULTS_SCHEMA_VERSION = "1.0"


class ConfidencePolicy(BaseModel):
    """
    Configurable thresholds that govern when ML predictions are converted
    into evidence vs. when the system abstains.
    
    Three zones:
      prob >= positive_threshold  → POSITIVE (emit evidence)
      prob <= negative_threshold  → NEGATIVE (no evidence)
      otherwise                   → ABSTAIN  (uncertain, do not act)
    
    Defaults are intentionally conservative for a medical/skincare domain:
    false positives can trigger incorrect ingredient recommendations.
    """
    positive_threshold: float = 0.80
    negative_threshold: float = 0.20


class MLEvidenceResult(BaseModel):
    """
    The structured output of the adapter. This is what RecommendationService
    consumes — never raw ml_results dicts.
    """
    additional_concerns: List[str]
    decision: str  # "positive", "negative", "abstain", "error", "no_data"
    confidence: Optional[float] = None
    reason: str = ""


def adapt(ml_results: Optional[Dict[str, Any]], policy: ConfidencePolicy) -> MLEvidenceResult:
    """
    Pure function. Translates raw ML output into canonical evidence.
    
    Parameters:
        ml_results: The JSONB payload from SkinAnalysis.ml_results, or None.
        policy: The active confidence thresholds.
    
    Returns:
        MLEvidenceResult with zero or more canonical concern strings.
    """
    # No ML data available — nothing to contribute
    if ml_results is None:
        return MLEvidenceResult(
            additional_concerns=[],
            decision="no_data",
            reason="No ML results available"
        )

    # Verify status — if the inference itself failed, abstain
    status = ml_results.get("status", "")
    if status != "success":
        return MLEvidenceResult(
            additional_concerns=[],
            decision="error",
            reason=f"ML inference status: {status}"
        )

    # Extract confidence
    confidence = ml_results.get("acne_confidence")
    if confidence is None or not isinstance(confidence, (int, float)):
        return MLEvidenceResult(
            additional_concerns=[],
            decision="error",
            reason="Missing or invalid acne_confidence in ML results"
        )
    
    confidence = float(confidence)

    # Map ML concern names to canonical knowledge base concerns
    name_to_canonical = {
        "Acne": "acne_breakouts",
        "Post Acne Marks": "post_acne_marks",
        "Uneven Texture": "uneven_texture",
        "Oily Skin": "oily_skin",
        "Dehydration": "dehydration",
        "Dryness": "dryness",
        "Pigmentation": "hyperpigmentation",
        "Large Pores": "large_pores",
        "Redness": "redness"
    }

    additional_concerns = []
    reasons = []

    # Apply three-zone threshold policy for raw acne confidence (legacy support)
    if confidence >= policy.positive_threshold:
        additional_concerns.append("acne_breakouts")
        reasons.append(f"Confidence {confidence:.3f} >= positive threshold {policy.positive_threshold}")
    elif confidence <= policy.negative_threshold:
        reasons.append(f"Confidence {confidence:.3f} <= negative threshold {policy.negative_threshold}")
    else:
        reasons.append(f"Confidence {confidence:.3f} in abstention zone")

    # Extract dynamic concerns generated by InferenceService
    ml_concerns = ml_results.get("concerns", [])
    if isinstance(ml_concerns, list):
        for c in ml_concerns:
            if isinstance(c, dict) and "name" in c:
                canonical = name_to_canonical.get(c["name"])
                if canonical and canonical not in additional_concerns:
                    # If it was generated by InferenceService, we trust it as evidence
                    additional_concerns.append(canonical)
                    reasons.append(f"Detected concern: {c['name']} (severity: {c.get('severity', 'unknown')})")

    # Determine decision
    decision = "positive" if additional_concerns else "negative" if confidence <= policy.negative_threshold else "abstain"

    return MLEvidenceResult(
        additional_concerns=additional_concerns,
        decision=decision,
        confidence=confidence,
        reason="; ".join(reasons)
    )
