"""Add SkinAnalysis

Revision ID: 28da7e186a9b
Revises: f5434ca895ef
Create Date: 2026-07-10 15:16:42.305408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28da7e186a9b'
down_revision: Union[str, Sequence[str], None] = 'f5434ca895ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skin_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('questionnaire_submission_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('image_storage_key', sa.String(), nullable=False),
    sa.Column('preprocessing_version', sa.String(), nullable=False),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('created', 'uploaded', 'validating', 'ready', 'processing', 'completed', 'failed', 'rejected')", name='ck_skin_analyses_status'),
    sa.ForeignKeyConstraint(['questionnaire_submission_id'], ['questionnaire_submissions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_storage_key')
    )
    op.create_index('ix_skin_analyses_user_id_created_at', 'skin_analyses', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skin_analyses_user_id_created_at', table_name='skin_analyses')
    op.drop_table('skin_analyses')
    # ### end Alembic commands ###
