"""initial

Revision ID: 4c7869466a2c
Revises: 
Create Date: 2026-07-29 18:39:53.656310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7869466a2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('usage_instructions', sa.Text(), nullable=True),
    sa.Column('suitable_for', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_is_starred'), ['is_starred'], unique=False)

    op.create_table('system_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('exception', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('default_daily_limit', sa.Integer(), nullable=True),
    sa.Column('registration_enabled', sa.Boolean(), nullable=True),
    sa.Column('analysis_enabled', sa.Boolean(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('export_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_analysis_enabled', sa.Boolean(), nullable=True),
    sa.Column('recommendation_engine_enabled', sa.Boolean(), nullable=True),
    sa.Column('dataset_version', sa.String(), nullable=True),
    sa.Column('ml_model_version', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('daily_analysis_limit', sa.Integer(), nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('questionnaire_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questionnaire_submissions', schema=None) as batch_op:
        batch_op.create_index('ix_questionnaire_submissions_user_id_submitted_at', ['user_id', sa.literal_column('submitted_at DESC'), sa.literal_column('id DESC')], unique=False)

    op.create_table('skin_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skin_type', sa.Enum('oily', 'dry', 'combination', 'balanced_normal', 'unsure', name='skintype'), nullable=False),
    sa.Column('current_concerns', sa.JSON(), nullable=False),
    sa.Column('primary_goal', sa.Enum('fewer_visible_breakouts', 'calmer_looking_skin', 'more_even_looking_tone', 'improved_hydration', 'smoother_looking_texture', 'simpler_routine', 'prevention_focused_routine', name='primarygoal'), nullable=False),
    sa.Column('sensitivity_tendency', sa.Enum('low', 'moderate', 'high', 'unsure', name='sensitivitytendency'), nullable=False),
    sa.Column('routine_product_categories', sa.JSON(), nullable=False),
    sa.Column('active_ingredient_categories', sa.JSON(), nullable=False),
    sa.Column('sunscreen_frequency', sa.Enum('daily', 'most_days', 'occasionally', 'rarely', 'never', name='sunscreenfrequency'), nullable=False),
    sa.Column('routine_experience', sa.Enum('beginner', 'familiar', 'advanced', name='routineexperience'), nullable=False),
    sa.Column('clinician_directed_treatment', sa.Boolean(), nullable=False),
    sa.Column('known_reaction_categories', sa.JSON(), nullable=False),
    sa.Column('known_reaction_other_note', sa.String(length=200), nullable=True),
    sa.Column('preference_avoid_categories', sa.JSON(), nullable=False),
    sa.Column('climate', sa.Enum('hot_humid', 'hot_dry', 'cold_dry', 'temperate', 'mixed_seasonal', 'unsure', name='climate'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('skin_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('questionnaire_submission_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('image_storage_key', sa.String(), nullable=False),
    sa.Column('preprocessing_version', sa.String(), nullable=False),
    sa.Column('ml_results', sa.JSON(), nullable=True),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('created', 'uploaded', 'validating', 'ready', 'processing', 'completed', 'failed', 'rejected')", name='ck_skin_analyses_status'),
    sa.ForeignKeyConstraint(['questionnaire_submission_id'], ['questionnaire_submissions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_storage_key')
    )
    with op.batch_alter_table('skin_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_skin_analyses_user_id_created_at', ['user_id', sa.literal_column('created_at DESC')], unique=False)

    op.create_table('recommendation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('questionnaire_submission_id', sa.UUID(), nullable=False),
    sa.Column('skin_analysis_id', sa.UUID(), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('knowledge_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('safety_adjustments', sa.JSON(), nullable=False),
    sa.Column('routine_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_submission_id'], ['questionnaire_submissions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skin_analysis_id'], ['skin_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_runs', schema=None) as batch_op:
        batch_op.create_index('ix_recommendation_runs_user_id_created_at', ['user_id', sa.literal_column('created_at DESC')], unique=False)

    op.create_table('recommendation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('routine_step', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('explanation_codes', sa.JSON(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('ingredient', sa.String(), nullable=True),
    sa.Column('why', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('warnings', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_items', schema=None) as batch_op:
        batch_op.create_index('ix_recommendation_items_run_id', ['recommendation_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_items', schema=None) as batch_op:
        batch_op.drop_index('ix_recommendation_items_run_id')

    op.drop_table('recommendation_items')
    with op.batch_alter_table('recommendation_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_recommendation_runs_user_id_created_at')

    op.drop_table('recommendation_runs')
    with op.batch_alter_table('skin_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_skin_analyses_user_id_created_at')

    op.drop_table('skin_analyses')
    op.drop_table('skin_profiles')
    with op.batch_alter_table('questionnaire_submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_questionnaire_submissions_user_id_submitted_at')

    op.drop_table('questionnaire_submissions')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_provider_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('system_settings')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_timestamp'))

    op.drop_table('system_logs')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_is_starred'))
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    # ### end Alembic commands ###
