"""Add recommendation models

Revision ID: c024e9635afa
Revises: 28da7e186a9b
Create Date: 2026-07-11 11:03:52.350601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c024e9635afa'
down_revision: Union[str, Sequence[str], None] = '28da7e186a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('questionnaire_submission_id', sa.UUID(), nullable=False),
    sa.Column('skin_analysis_id', sa.UUID(), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('knowledge_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('safety_adjustments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_submission_id'], ['questionnaire_submissions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skin_analysis_id'], ['skin_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_runs_user_id_created_at', 'recommendation_runs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('recommendation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('routine_step', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('explanation_codes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_items_run_id', 'recommendation_items', ['recommendation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommendation_items_run_id', table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_index('ix_recommendation_runs_user_id_created_at', table_name='recommendation_runs')
    op.drop_table('recommendation_runs')
    # ### end Alembic commands ###
