"""Admin panel sprint

Revision ID: c2ef0f41b6b5
Revises: 72cae1ae29ec
Create Date: 2026-07-18 10:33:52.125243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ef0f41b6b5'
down_revision: Union[str, Sequence[str], None] = '72cae1ae29ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_logs_timestamp'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('system_settings')
    op.drop_table('notifications')
    op.alter_column('auth_sessions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('auth_sessions', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('questionnaire_submissions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('questionnaire_submissions', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('recommendation_items', sa.Column('product_type', sa.String(), nullable=True))
    op.add_column('recommendation_items', sa.Column('ingredient', sa.String(), nullable=True))
    op.add_column('recommendation_items', sa.Column('why', sa.String(), nullable=True))
    op.add_column('recommendation_items', sa.Column('instructions', sa.String(), nullable=True))
    op.add_column('recommendation_items', sa.Column('frequency', sa.String(), nullable=True))
    op.add_column('recommendation_items', sa.Column('warnings', sa.String(), nullable=True))
    op.alter_column('recommendation_items', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('recommendation_items', 'recommendation_run_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('recommendation_runs', sa.Column('routine_data', sa.JSON(), nullable=True))
    op.alter_column('recommendation_runs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('recommendation_runs', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('recommendation_runs', 'questionnaire_submission_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('recommendation_runs', 'skin_analysis_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('skin_analyses', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('skin_analyses', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('skin_analyses', 'questionnaire_submission_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('skin_profiles', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('skin_profiles', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('daily_analysis_limit', sa.Integer(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('users', 'daily_analysis_limit')
    op.drop_column('users', 'username')
    op.alter_column('skin_profiles', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('skin_profiles', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('skin_analyses', 'questionnaire_submission_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('skin_analyses', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('skin_analyses', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('recommendation_runs', 'skin_analysis_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('recommendation_runs', 'questionnaire_submission_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('recommendation_runs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('recommendation_runs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('recommendation_runs', 'routine_data')
    op.alter_column('recommendation_items', 'recommendation_run_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('recommendation_items', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('recommendation_items', 'warnings')
    op.drop_column('recommendation_items', 'frequency')
    op.drop_column('recommendation_items', 'instructions')
    op.drop_column('recommendation_items', 'why')
    op.drop_column('recommendation_items', 'ingredient')
    op.drop_column('recommendation_items', 'product_type')
    op.alter_column('questionnaire_submissions', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('questionnaire_submissions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('auth_sessions', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('auth_sessions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_table('notifications',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=False),
    sa.Column('link', sa.VARCHAR(), nullable=True),
    sa.Column('read', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('maintenance_mode', sa.BOOLEAN(), nullable=True),
    sa.Column('registration_open', sa.BOOLEAN(), nullable=True),
    sa.Column('max_upload_mb', sa.INTEGER(), nullable=True),
    sa.Column('data_retention_days', sa.INTEGER(), nullable=True),
    sa.Column('ml_confidence_threshold', sa.INTEGER(), nullable=True),
    sa.Column('dataset_version', sa.VARCHAR(), nullable=True),
    sa.Column('ml_model_version', sa.VARCHAR(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('event', sa.VARCHAR(length=50), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###
