"""Add SkinProfile and QuestionnaireSubmission

Revision ID: f5434ca895ef
Revises: 1a2b3c4d5e6f
Create Date: 2026-07-10 13:57:26.880876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5434ca895ef'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questionnaire_submissions_user_id_submitted_at', 'questionnaire_submissions', ['user_id', sa.literal_column('submitted_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('skin_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skin_type', sa.Enum('oily', 'dry', 'combination', 'balanced_normal', 'unsure', name='skintype'), nullable=False),
    sa.Column('current_concerns', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('primary_goal', sa.Enum('fewer_visible_breakouts', 'calmer_looking_skin', 'more_even_looking_tone', 'improved_hydration', 'smoother_looking_texture', 'simpler_routine', 'prevention_focused_routine', name='primarygoal'), nullable=False),
    sa.Column('sensitivity_tendency', sa.Enum('low', 'moderate', 'high', 'unsure', name='sensitivitytendency'), nullable=False),
    sa.Column('routine_product_categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('active_ingredient_categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('sunscreen_frequency', sa.Enum('daily', 'most_days', 'occasionally', 'rarely', 'never', name='sunscreenfrequency'), nullable=False),
    sa.Column('routine_experience', sa.Enum('beginner', 'familiar', 'advanced', name='routineexperience'), nullable=False),
    sa.Column('clinician_directed_treatment', sa.Boolean(), nullable=False),
    sa.Column('known_reaction_categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('known_reaction_other_note', sa.String(length=200), nullable=True),
    sa.Column('preference_avoid_categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('climate', sa.Enum('hot_humid', 'hot_dry', 'cold_dry', 'temperate', 'mixed_seasonal', 'unsure', name='climate'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skin_profiles')
    op.drop_index('ix_questionnaire_submissions_user_id_submitted_at', table_name='questionnaire_submissions')
    op.drop_table('questionnaire_submissions')
    # ### end Alembic commands ###
